### ISSUE TITLE
great work but possible to have a code to convert interface types to bytes?

### ISSUE THREAD

**Issue by gitmko0** [glycerine/greenpack#10]
we are using gob
https://pastebin.com/U5hA8ZmT

to convert interface to bytes. do you have a solution using greenpack / zebrapack?

**Comment by glycerine** [comment]
As the README says, in greenpack, interfaces are serialized as the concrete type they point to. This can require that the underlying concrete type implement two helper methods, as the README discusses on the front page.

**Comment by gitmko0** [comment]
care to share a working demo of how that works?

**Comment by glycerine** [comment]
I'm sorry you are too dense to take the hint. It is right there in the README.  Do your homework before pestering busy people.
