### ISSUE TITLE
Nested Maps

### ISSUE THREAD

**Issue by sasloz** [glycerine/greenpack#12]
Hi! 

Could it be possible that nested maps do not always work as expected? 

"map[int64]map[int64]OurType" works fine.

"map[int64]map[int8]OurType" does not write any data. 

It looks like the generated EncodeMsg function then sort of forgets "OurType" etc.

Thank you!

**Comment by glycerine** [comment]
possibly... I seem to recall writing advice in the docs about needing to interpose a struct at some point. I'm on the road at the moment. Please remind me if I haven't replied more substantially by later in the week.

**Comment by glycerine** [comment]
Unfortunately I don't have time to look into this more. But I'm happy to accept a PR if you would be so kind as to include a test case.
