### ISSUE TITLE
i would like to have a [][]byte to []byte serializer and deserializer.

### ISSUE THREAD

**Issue by kolinfluence** [glycerine/greenpack#14]
i would like to have a [][]byte to []byte serializer and deserializer. how do i use it with greenpack as a package?

**Comment by glycerine** [comment]
I've added a demonstration for you in https://github.com/glycerine/greenpack/blob/master/demo/bytes2d.go

**Comment by kolinfluence** [comment]
@glycerine it's working really well. thx. if there's a sponsoring coffee section, would like to buy u a coffee.

by the way, is there a possibility to check for a []byte "value" in the Marshalled message without unmarshalling it first?

something like a Has() function.

is there one for other types of marshalled message? e.g. some "key" -> "value" thing.

**Comment by glycerine** [comment]
It is just msgpack(version 2, with binaries and strings being different) serialization underneath. Refer to the msgpack.org spec for how the bytes are laid out ( https://github.com/msgpack/msgpack/blob/master/spec.md ). Of course you can scan the bytes for whatever you wish.

Here is a function that can be helpful for reading the framing of the serialized bytes.

~~~
import (
    "encoding/binary"
    "fmt"
)

// DecodeMsgpackBinArrayHeader parses the first 2-5 bytes of a msgpack-format serialized binary array
// and returns the headerSize, payloadSize and totalFramesize for the frame the starts at p[0].
func DecodeMsgpackBinArrayHeader(p []byte) (headerSize int, payloadSize int, totalFrameSize int, err error) {
    lenp := len(p)

    switch p[0] {
    case 0xc4: // msgpackBin8
        if lenp < 2 {
            err = fmt.Errorf("DecodeMsgpackBinArrayHeader error: p len (%d) too small", lenp)
            return
        }
        headerSize = 2
        payloadSize = int(p[1])
    case 0xc5: // msgpackBin16
        if lenp < 3 {
            err = fmt.Errorf("DecodeMsgpackBinArrayHeader error: p len (%d) too small", lenp)
            return
        }
        headerSize = 3
        payloadSize = int(binary.BigEndian.Uint16(p[1:3]))
    case 0xc6: // msgpackBin32
        if lenp < 5 {
            err = fmt.Errorf("DecodeMsgpackBinArrayHeader error: p len (%d) too small", lenp)
            return
        }
        headerSize = 5
        payloadSize = int(binary.BigEndian.Uint32(p[1:5]))
    }

    totalFrameSize = headerSize + payloadSize
    return
}
~~~
