### ISSUE TITLE
works great! is there an smf equivalent (flatbuffers) for greenpack?

### ISSUE THREAD

**Issue by kolinfluence** [glycerine/greenpack#15]
was using greenpack and the zero alloc is a great feature. 
i was thinking about the wire transfer (to be zero alloc too) since greenpack compares itself with protobuf.
and i thought about this: https://github.com/smfrpc/smf

which makes me wonder if greenpack can do an equivalent wire transfer thingy
https://github.com/smfrpc/smf-go

1. is this on the roadmap? 
2. is it difficult to implement using greenpack?
3. possible to get it done?

**Comment by glycerine** [comment]
There are no plans to integrate an RPC system. Just use any of the multitude of RPC systems out there.

**Comment by glycerine** [comment]
@kolinfluence As it turns out I did recently do an RPC system that works with greenpack by default; and then I recalled your request. You can find it here: https://github.com/glycerine/rpc25519
