### ISSUE TITLE
Any c++ compatible , cross compatible with golang passing?

### ISSUE THREAD

**Issue by kolinfluence** [glycerine/greenpack#16]
i have a well written golang server but hope to use c++ client to pass the data to golang

**Comment by glycerine** [comment]
greenpack is just a convention (for encoding keys in maps, using names, zids, and type hints) when using msgpack, so any of the 8 or so C/C++ msgpack bindings listed here https://msgpack.org/ could get you started. I don't know of any other specific to greenpack C/C++ libraries. If you make one, let me know and I can list the link to your repo.
