### ISSUE TITLE
encoding then decoding produces different data type

### ISSUE THREAD

**Issue by chrislusf** [glycerine/greenpack#4]
The test works: https://github.com/chrislusf/gleam/blob/master/util/row_read_write_test.go

But if I change the originalKey to uint32, the test fails. The decoded type is int64.

    package util

    import (
        "testing"
    )

    func TestEncodeDecode(t *testing.T) {

        originalKey := uint32(2349234)

        originalData := []interface{}{
            originalKey,
            "jkjkj",
            123,
            "zx,mcv",
        }

        originalTs := Now()

        encodedRow, _ := encodeRow(*NewRow(originalTs, originalData...))

        t.Logf("encoded: %x", encodedRow)

        row, _ := DecodeRow(encodedRow)

        if originalTs != row.T {
            t.Errorf("Failed to decode ts %d => %d", originalTs, row.T)
        }

        if key, ok := row.K[0].(uint32); ok {
            if key != originalKey {
                t.Errorf("Failed to decode key %d => %d", originalKey, key)
            }
        } else {
            t.Errorf("Failed to get matching key type %d => %d", originalKey, key)
        }

        if len(row.V) != len(originalData)-1 {
            t.Errorf("Failed to decode to the same length %d => %d", len(originalData), len(row.V)-1)
        }

    }

**Comment by glycerine** [comment]
If you decode to and from a struct, then we have type info from the struct and can do the right thing. Without that kind of information, how can you expect the decoder to know what size you want?

It has to be conservative, and you'll need to manually convert it down to what you want.

**Comment by chrislusf** [comment]
I thought the type info is encoded also?

**Comment by glycerine** [comment]
update: (ignore my previous incorrect comment). msgpack type bytes distinguish between signed and unsigned integers, but most implementations fudge that for compression. 

I think you're saying you'd like a mode where the type info is accurate even when not using structs... is that sufficient/what you're thinking of?

**Comment by chrislusf** [comment]
How to enable non-struct full type info? No need to follow msgpack exactly.

**Comment by glycerine** [comment]
It's easy to do, but creates some issues for backward compatibility. I forked and made a separate project with support for "true" integer types. I called it `truepack`. See
https://github.com/glycerine/truepack
