### ISSUE TITLE
Use standardized generated comment to avoid linter warnings

### ISSUE THREAD

**Issue by kdar** [glycerine/greenpack#5]
The following comment on top of generated msgpack files will prevent linters from spewing warnings:

```
// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.
```

Formalized here: https://golang.org/s/generatedcode,

**Comment by glycerine** [comment]
Done. Thanks @kdar.

**Comment by kdar** [comment]
I failed to mention it needs to be the first line for the linters to ignore it. You can add a newline after it so it doesn't get `godoc`ed.

**Comment by glycerine** [comment]
done in 1f00535

**Comment by kdar** [comment]
Works perfectly!
